<?php

/**
 * Implements hook_theme().
 */
function farm_contact_theme($existing, $type, $theme, $path) {
  return [
    'farm_contact_profile' => [
      'variables' => [
        'contacts' => NULL,
      ],
      'template' => 'farm-contact-profile',
      'path' => \Drupal::service('extension.list.module')->getPath('farm_contact') . '/templates',
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK() for farm_contact_profile template.
 */
function farm_contact_preprocess_farm_contact_profile(&$variables) {
  if (isset($variables['#variables'])) {
    foreach ($variables['#variables'] as $key => $value) {
      $variables[$key] = $value;
    }
  }
}


/**
 * Prepares variables for contact templates.
 */
function farm_contact_preprocess_contact(array &$variables) {
  $contact = $variables['elements']['#contact'] ?? NULL;

  if ($contact) {
    $variables['farm_contact'] = $contact;
  }
}
